export const IMAGES = {
  hero: {
    lightMode: '/images/hero/light-mode.png',
    darkMode:  '/images/hero/dark-mode.png',
    video:     '/images/hero/hero-video.mp4',
  },
  about: {
    hero:         '/images/about/hero.png',
    construction: '/images/about/pool-construction.png',
  },
  services: {
    swimmingPool:       '/images/services/hub/swimming-pool.png',
    turnkeyHero:        '/images/services/turnkey-projects/hero.png',
    accessoriesHero:    '/images/services/accessories/hero.png',
    accessoriesLadder:  '/images/services/accessories/ladder.jpg',
    skimmerEdge:        '/images/services/accessories/standard-skimmer-edge.png',
    overflowEdge:       '/images/services/accessories/deck-level-overflow-edge.png',
    renovationHero:     '/images/services/renovation/hero.png',
    renovation:         [
      '/images/services/renovation/1.png',
      '/images/services/renovation/2.png',
      '/images/services/renovation/3.png',
    ],
    readymadeHero:      '/images/services/readymade-pools/hero.png',
    readymadeAdvantages: [
      '/images/services/readymade-pools/Advantage-01.png',
      '/images/services/readymade-pools/Advantage-02.png',
      '/images/services/readymade-pools/Advantage-03.png',
      '/images/services/readymade-pools/Advantage-04.png',
      '/images/services/readymade-pools/Advantage-05.png',
    ],
  },
  poolTypes: {
    private:      '/images/pool-types/private.jpg',
    commercial:   '/images/pool-types/commercial.jpg',
    recreational: '/images/pool-types/recreational.jpg',
    competition:  '/images/pool-types/competition.jpg',
    vanishingEdge:'/images/pool-types/vanishing-edge.png',
    overflow:     '/images/pool-types/overflow.png',
    skimmer:      '/images/pool-types/skimmer.png',
    readymade:    '/images/pool-types/readymade.png',
  },
  gallery: {
    light: [
      '/images/gallery/light/gallery-01.png',
      '/images/gallery/light/gallery-02.png',
      '/images/gallery/light/gallery-03.png',
      '/images/gallery/light/gallery-04.png',
      '/images/gallery/light/gallery-05.png',
      '/images/gallery/light/gallery-06.png',
      '/images/gallery/light/gallery-07.png',
      '/images/gallery/light/gallery-08.png',
      '/images/gallery/light/gallery-09.png',
      '/images/gallery/light/gallery-10.png',
    ],
    dark: [
      '/images/gallery/dark/gallery-01.png',
      '/images/gallery/dark/gallery-02.png',
      '/images/gallery/dark/gallery-03.png',
      '/images/gallery/dark/gallery-04.png',
      '/images/gallery/dark/gallery-05.png',
      '/images/gallery/dark/gallery-06.png',
      '/images/gallery/dark/gallery-07.png',
      '/images/gallery/dark/gallery-08.png',
      '/images/gallery/dark/gallery-09.png',
      '/images/gallery/dark/gallery-10.png',
    ],
  },
  locations: {
    pune:       '/images/locations/pune.jpg',
    nashik:     '/images/locations/nashik.jpg',
    kolhapur:   '/images/locations/kolhapur.jpg',
    sindhudurg: '/images/locations/alibag.jpg', 
    goa:        '/images/locations/goa.jpg',
    udaipur:    '/images/locations/udaipur.jpg',
  },
  equipment: {
    hero:                 '/images/products/equipment-catalogue/hero.png',
    fSeries:              '/images/products/equipment-catalogue/filters/f-series.png',
    bSeries:              '/images/products/equipment-catalogue/filters/b-series.png',
    mSeries:              '/images/products/equipment-catalogue/filters/m-series.png',
    msSeries:             '/images/products/equipment-catalogue/filters/ms-series.png',
    mxbSeries:            '/images/products/equipment-catalogue/pumps/mxb-series.png',
    mrbSeries:            '/images/products/equipment-catalogue/pumps/mrb-series.png',
    mtxSeries:            '/images/products/equipment-catalogue/pumps/mtx-series.png',
    minderchlor:          '/images/products/equipment-catalogue/disinfection/minderchlor-salt-chlorinator.png',
    chemicalTabletFeeder: '/images/products/equipment-catalogue/disinfection/chemical-tablet-feeder.png',
    dosingstar:           '/images/products/equipment-catalogue/disinfection/dosingstar-dosing-pump.png',
    bpSeries:             '/images/products/equipment-catalogue/disinfection/bp-series.png',
    hydrosmart:           '/images/products/equipment-catalogue/disinfection/hydrosmart-pool.png',
    poolVacuum:           '/images/products/equipment-catalogue/disinfection/pool-vacuum.png',
    heavyDutyVacuumHead:  '/images/products/equipment-catalogue/disinfection/heavy-duty-ss-vacuum-head.png',
    aluminumVacuumHead:   '/images/products/equipment-catalogue/disinfection/aluminum-head-14.png',
    vacuumHeadSideBrush:  '/images/products/equipment-catalogue/disinfection/vacuum-head-side-brush.png',
    ssAlgaeBrushes:       '/images/products/equipment-catalogue/disinfection/ss-algae-brushes.png',
    polesWithGripLock:    '/images/products/equipment-catalogue/disinfection/poles-with-grip-lock.png',
    poolHose:             '/images/products/equipment-catalogue/disinfection/pool-hose.png',
    poolPlastic:          '/images/products/equipment-catalogue/disinfection/pool-plastic.png',
    poolGeneral:          '/images/products/equipment-catalogue/disinfection/pool-general.png',
  },
  tilesHero: '/images/services/pool-tiles/hero.png',
  tiles: [
    '/images/services/pool-tiles/1.png',
    '/images/services/pool-tiles/2.png',
    '/images/services/pool-tiles/3.png',
    '/images/services/pool-tiles/4.png',
    '/images/services/pool-tiles/5.png',
    '/images/services/pool-tiles/6.png',
    '/images/services/pool-tiles/7.png',
    '/images/services/pool-tiles/8.png',
  ],
  waterFeatures: {
    hero:     '/images/services/water-features/hero.png',
    geyser:   '/images/services/water-features/geyser-jet-fountain.png',
    foam:     '/images/services/water-features/foam-jet-fountain.png',
    bell:     '/images/services/water-features/bell-jet-fountain.png',
    dandelion:'/images/services/water-features/dandelion.png',
    bubbler:  '/images/services/water-features/bubbler-jet-fountain.png',
    curtains: '/images/services/water-features/water-curtains.png',
    laminar:  'https://images.unsplash.com/photo-1543881477-8d022b70f032?auto=format&fit=crop&w=800&q=80',
    tiered:   'https://images.unsplash.com/photo-1549480017-d7741829e1eb?auto=format&fit=crop&w=800&q=80',
    musical:  'https://images.unsplash.com/photo-1510006851064-e6056cd0e3a8?auto=format&fit=crop&w=800&q=80',
  },
  specialty: {
    hero: '/images/products/specialty-installations/hero.png',
    adhesiveGrout: [
      '/images/products/specialty-installations/adhesive-grout/1.png',
      '/images/products/specialty-installations/adhesive-grout/2.png',
      '/images/products/specialty-installations/adhesive-grout/3.png',
      '/images/products/specialty-installations/adhesive-grout/4.png',
    ],
    sunbath: [
      '/images/products/specialty-installations/sunbath/1.png',
      '/images/products/specialty-installations/sunbath/2.png',
      '/images/products/specialty-installations/sunbath/3.png',
      '/images/products/specialty-installations/sunbath/4.png',
      '/images/products/specialty-installations/sunbath/5.png',
    ],
    jacuzzi: [
      '/images/products/specialty-installations/jacuzzi/1.png',
      '/images/products/specialty-installations/jacuzzi/2.png',
      '/images/products/specialty-installations/jacuzzi/3.png',
      '/images/products/specialty-installations/jacuzzi/4.png',
      '/images/products/specialty-installations/jacuzzi/5.png',
    ],
  },
  sections: {
    testimonialsBg: '/images/sections/testimonials-bg.jpg',
    footer:         '/images/sections/footer.jpg',
    liquidEffect:   '/images/sections/liquid-effect.jpg',
  },
  clients: {
    amanoraParkTown:        '/images/client/amanora-park-town.png',
    anantiEstate:           '/images/client/ananti-estate.png',
    csbSankalp:             '/images/client/csb-sankalp.png',
    dorleGroup:             '/images/client/dorle-group.png',
    gera:                   '/images/client/gera.png',
    hornbillResort:         '/images/client/hornbill-resort.png',
    kRahejaCorp:            '/images/client/k-raheja-corp.png',
    karandiValley:          '/images/client/karandi-valley.png',
    leverageGreens:         '/images/client/leverage-greens.png',
    matrixConstruction:     '/images/client/matrix-construction.png',
    namrataOmkar:           '/images/client/namrata-omkar.png',
    oceanParkResort:        '/images/client/ocean-park-resort.png',
    paramountBuilders:      '/images/client/paramount-builders.png',
    paranjapeSchemes:       '/images/client/paranjape-schemes.png',
    prabhaveeGroup:         '/images/client/prabhavee-group.png',
    prajayEngineerSyndicate:'/images/client/prajay-engineer-syndicate.png',
    reliance:               '/images/client/reliance.png',
    renukaDevelopers:       '/images/client/renuka-developers.png',
    samudraSairCottage:     '/images/client/samudra-sair-cottage.png',
    sanjayGhodawatGroup:    '/images/client/sanjay-ghodawat-group.png',
    sanskritiSchoolPune:    '/images/client/sanskriti-school-pune.png',
    utsavHomes:             '/images/client/utsav-homes.png',
  },
} as const;
